apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name | quote }}
  annotations:
    console.alpha.openshift.io/overview-app-route: "true"
  name: {{ .Values.name | quote }}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.component | quote }}
