apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.name | quote }}
    component: {{ .Values.component | quote }}
