name: Verify PR Build
on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'

jobs:
  verify-build:
    name: Verify PR Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Apicurito Checkout
        uses: actions/checkout@v3
      - name: Build Apicurito
        run: |
          cd /home/runner/work/apicurito/apicurito
          mvn clean install -Dgit.commit.id.plugin.skip=true -D::image
